version: "3.8"

services:
  mysql:
    container_name: fiap_sa_order_service_db
    image: mysql:8.4
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../.mysqldata8-0:/var/lib/mysql
      - ./testdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  app:
    container_name: fiap_sa_order_service_app
    ports:
      - 8082:8082
    depends_on:
      - mysql
    volumes:
      - .:/app
    build:
      context: .
      target: dev
    command: tail -f /dev/null
